services:
  one-frame:
    image: paidyinc/one-frame
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
  vault:
    image: hashicorp/vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_TOKEN}"
      VAULT_TOKEN: "${VAULT_TOKEN}"
      ONE_FRAME_TOKEN: ${ONE_FRAME_TOKEN}
      REDIS_TOKEN: ${REDIS_TOKEN}
    healthcheck:
      test: "vault login ${VAULT_TOKEN}"
      interval: 1s
    volumes:
      - ./vault-entrypoint.sh:/vault-entrypoint.sh
    entrypoint: [ "/vault-entrypoint.sh" ]
    networks:
      - app-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $REDIS_TOKEN ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: [ "redis-server", "--requirepass", "${REDIS_TOKEN}" ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
