name: DEFAULT PIPELINE
on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set JDK17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Set up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.8.0
      - name: Validate codecov.yml
        run: curl --data-binary @codecov.yml https://codecov.io/validate
      - name: Format Check & Compile
        run: |
          cd forex-mtl
          sbt scalafmtCheckAll
          sbt clean compile
      - name: Test and Coverage
        run: |
          cd forex-mtl
          sbt coverage test
          sbt coverageReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set JDK17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Set up SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.8.0
      - name: Start Forex MTL service
        env:
          ONE_FRAME_TOKEN: ${{ secrets.ONE_FRAME_TOKEN }}
          VAULT_TOKEN: "random-vault-token"
          REDIS_TOKEN: "random-redis-token"
        run: |
          cd forex-mtl
          docker compose -f integration-test.yml up -d
      - name: Check service health
        run: |
          cd forex-mtl
          docker compose -f integration-test.yml ps
      - name: Run integration tests
        run: |
          cd forex-mtl
          sbt integrationTest
      - name: Cleanup
        if: always()
        run: |
          cd forex-mtl
          docker compose -f integration-test.yml down -v
